"""Deterministic single-cycle simulation helpers for tests and examples.

The simulator does not emulate TWS execution. It is intentionally small and
conservative so fixed price paths can validate the application's strategy rules:

* anchor reset while waiting for the initial drop;
* app-side BUY trailing-stop trigger after the drop;
* minimum-profit activation of the SELL trailing-stop;
* app-side SELL trailing-stop trigger after activation;
* RTH-open/RTH-closed gating before app-created order placement.

Live trading uses broker-native IBKR trailing orders. This module is only
for automated tests, documentation examples, and repeatable local simulations.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Iterable, Sequence

from .models import CycleState, Stage, StrategySettings
from .strategy import StrategyAction, StrategyEngine


@dataclass(slots=True)
class SimulatedEvent:
    """One trace row generated by ``simulate_price_path``."""

    index: int
    price: float
    stage: str
    message: str


@dataclass(slots=True)
class SimulationResult:
    """Complete deterministic outcome of a simulated single-ticker cycle."""

    cycle: CycleState
    events: list[SimulatedEvent] = field(default_factory=list)
    actions: list[StrategyAction] = field(default_factory=list)

    @property
    def completed(self) -> bool:
        return self.cycle.stage == Stage.CYCLE_COMPLETE


class NativeTrailSimulator:
    """Simple app-side model of a native trailing-stop order.

    BUY trailing stop:
        Tracks the lowest price after submission and triggers when price rebounds
        to ``lowest * (1 + trail_pct)``.

    SELL trailing stop:
        Tracks the highest price after submission and triggers when price falls
        to ``highest * (1 - trail_pct)``.

    The live bot delegates this to TWS/IBKR; this class exists only to make
    automatic tests deterministic without a broker connection.
    """

    def __init__(self, side: str, initial_stop: float, trail_pct: float):
        side = side.upper().strip()
        if side not in {"BUY", "SELL"}:
            raise ValueError("side must be BUY or SELL")
        if not (0.0 < float(trail_pct) < 100.0):
            raise ValueError("trail_pct must be between 0 and 100")
        self.side = side
        self.trail_pct = float(trail_pct)
        self.stop_price = float(initial_stop)
        trail = self.trail_pct / 100.0
        # Initialize the tracked extreme from the submitted stop price. Without
        # this, a SELL trail whose first observed tick is lower than the
        # submission price could incorrectly move the stop down, and a BUY trail
        # whose first observed tick is higher could incorrectly move the stop up.
        # Native trailing stops should only move in the favorable direction from
        # their submission baseline.
        if self.side == "BUY":
            self.low_watermark: float | None = self.stop_price / (1.0 + trail)
            self.high_watermark: float | None = None
        else:
            self.low_watermark = None
            self.high_watermark = self.stop_price / (1.0 - trail)

    def update(self, price: float) -> bool:
        price = float(price)
        if self.side == "BUY":
            if self.low_watermark is None or price < self.low_watermark:
                self.low_watermark = price
                self.stop_price = price * (1.0 + self.trail_pct / 100.0)
            return price >= self.stop_price
        if self.high_watermark is None or price > self.high_watermark:
            self.high_watermark = price
            self.stop_price = price * (1.0 - self.trail_pct / 100.0)
        return price <= self.stop_price


def simulate_price_path(
    settings: StrategySettings,
    prices: Sequence[float] | Iterable[float],
    *,
    account: str = "SIM",
    cycle_number: int = 1,
    realized_net_profit: float = 0.0,
    rth_mask: Sequence[bool] | None = None,
    fill_at_stop: bool = True,
) -> SimulationResult:
    """Run a deterministic single-cycle simulation with supplied prices.

    Parameters
    ----------
    settings:
        Strategy settings to simulate.
    prices:
        Ordered input price path. The first price sets the initial anchor.
    rth_mask:
        Optional list of booleans aligned with ``prices``. ``False`` means the
        app-side RTH guard is closed for that price tick, so new BUY/SELL order
        submissions are blocked.
    fill_at_stop:
        If true, simulated fills occur at the current native-trail stop price.
        If false, fills occur at the current input price. The default is useful
        for checking configured trigger/stop levels; the latter is useful for
        slippage-style tests.
    """

    price_list = [float(value) for value in prices]
    if not price_list:
        raise ValueError("At least one price is required.")
    for value in price_list:
        if value <= 0:
            raise ValueError("All simulated prices must be positive.")

    cycle = StrategyEngine.start_cycle(settings, cycle_number, account, price_list[0], realized_net_profit)
    result = SimulationResult(cycle=cycle)
    buy_trail: NativeTrailSimulator | None = None
    protective_sell_trail: NativeTrailSimulator | None = None
    sell_trail: NativeTrailSimulator | None = None

    def process_actions(idx: int, price: float, actions: list[StrategyAction]) -> None:
        nonlocal cycle, buy_trail, protective_sell_trail, sell_trail
        result.actions.extend(actions)
        for action in actions:
            if action.action_type == "PLACE_BUY_TRAIL":
                cycle = StrategyEngine.on_order_submitted(cycle, action.payload["order_ref"], 1000 + idx, 2000 + idx, "Submitted")
                buy_trail = NativeTrailSimulator("BUY", action.payload["initial_stop_price"], action.payload["trailing_percent"])
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, "submitted BUY trailing-stop"))
            elif action.action_type == "PLACE_BUY_MARKET":
                cycle = StrategyEngine.on_order_submitted(cycle, action.payload["order_ref"], 1000 + idx, 2000 + idx, "Submitted")
                fill_price = price
                cycle, follow_actions = StrategyEngine.on_buy_fill(cycle, filled_qty=cycle.quantity, avg_fill_price=fill_price, status="Filled", commission=0.0)
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"simulated BUY market fill @ {fill_price:.4f}"))
                process_actions(idx, fill_price, follow_actions)
            elif action.action_type == "PLACE_PROTECTIVE_SELL_TRAIL":
                cycle = StrategyEngine.on_order_submitted(cycle, action.payload["order_ref"], 5000 + idx, 6000 + idx, "Submitted")
                protective_sell_trail = NativeTrailSimulator("SELL", action.payload["initial_stop_price"], action.payload["trailing_percent"])
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, "submitted protective SELL trailing-stop"))
            elif action.action_type == "CANCEL_ORDER" and action.payload.get("role") == "protective_sell":
                if cycle.protective_sell_order_ref:
                    cycle = StrategyEngine.on_order_submitted(cycle, cycle.protective_sell_order_ref, cycle.protective_sell_order_id, cycle.protective_sell_perm_id, "Cancelled")
                protective_sell_trail = None
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, "cancelled protective SELL trailing-stop"))
            elif action.action_type == "PLACE_SELL_TRAIL":
                cycle = StrategyEngine.on_order_submitted(cycle, action.payload["order_ref"], 3000 + idx, 4000 + idx, "Submitted")
                sell_trail = NativeTrailSimulator("SELL", action.payload["initial_stop_price"], action.payload["trailing_percent"])
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, "submitted SELL trailing-stop"))
            elif action.action_type == "PLACE_SELL_MARKET":
                cycle = StrategyEngine.on_order_submitted(cycle, action.payload["order_ref"], 3000 + idx, 4000 + idx, "Submitted")
                fill_price = price
                cycle = StrategyEngine.on_sell_fill(cycle, filled_qty=cycle.buy_filled_qty, avg_fill_price=fill_price, status="Filled", commission=0.0)
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"simulated SELL market fill @ {fill_price:.4f}"))

    for idx, price in enumerate(price_list):
        is_rth = True if rth_mask is None or idx >= len(rth_mask) else bool(rth_mask[idx])

        if cycle.stage == Stage.BUY_TRAIL_ACTIVE and buy_trail is not None:
            if buy_trail.update(price):
                fill_price = buy_trail.stop_price if fill_at_stop else price
                cycle, actions = StrategyEngine.on_buy_fill(
                    cycle,
                    filled_qty=cycle.quantity,
                    avg_fill_price=fill_price,
                    status="Filled",
                    commission=0.0,
                )
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"simulated BUY fill @ {fill_price:.4f}"))
                process_actions(idx, fill_price, actions)
                buy_trail = None
            else:
                cycle.last_price = price
                cycle.touch()
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"BUY trail stop {buy_trail.stop_price:.4f}"))

        elif cycle.stage == Stage.WAIT_RISE_TRIGGER and protective_sell_trail is not None:
            cycle.last_price = price
            if protective_sell_trail.update(price):
                fill_price = protective_sell_trail.stop_price if fill_at_stop else price
                cycle = StrategyEngine.on_protective_sell_fill(
                    cycle,
                    filled_qty=cycle.buy_filled_qty,
                    avg_fill_price=fill_price,
                    status="Filled",
                    commission=0.0,
                )
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"simulated protective SELL fill @ {fill_price:.4f}"))
                protective_sell_trail = None
            else:
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"protective SELL trail stop {protective_sell_trail.stop_price:.4f}"))
                cycle, actions = StrategyEngine.on_price_update(
                    cycle,
                    price,
                    is_rth=is_rth,
                    rth_message="simulation RTH closed",
                )
                process_actions(idx, price, actions)

        elif cycle.stage == Stage.SELL_TRAIL_ACTIVE and sell_trail is not None:
            if sell_trail.update(price):
                fill_price = sell_trail.stop_price if fill_at_stop else price
                cycle = StrategyEngine.on_sell_fill(
                    cycle,
                    filled_qty=cycle.buy_filled_qty,
                    avg_fill_price=fill_price,
                    status="Filled",
                    commission=0.0,
                )
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"simulated SELL fill @ {fill_price:.4f}"))
                sell_trail = None
            else:
                cycle.last_price = price
                cycle.touch()
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, f"SELL trail stop {sell_trail.stop_price:.4f}"))

        elif cycle.stage in {Stage.WAIT_INITIAL_DROP, Stage.WAIT_RISE_TRIGGER}:
            cycle, actions = StrategyEngine.on_price_update(
                cycle,
                price,
                is_rth=is_rth,
                rth_message="simulation RTH closed",
            )
            process_actions(idx, price, actions)
            if not actions:
                result.events.append(SimulatedEvent(idx, price, cycle.stage.value, "strategy price update"))

        else:
            result.events.append(SimulatedEvent(idx, price, cycle.stage.value, "terminal/no-op"))

        result.cycle = cycle
        if cycle.stage == Stage.CYCLE_COMPLETE:
            break

    return result
